package org.merlin204.mimic.entity.ai;

import com.merlin204.avalon.entity.ai.AvalonCombatBehaviors;
import com.merlin204.avalon.entity.ai.AvalonCombatBehaviors.Behavior;
import com.merlin204.avalon.entity.ai.AvalonCombatBehaviors.BehaviorSeries;
import com.merlin204.avalon.entity.ai.AvalonCombatBehaviors.Builder;
import com.merlin204.avalon.entity.condition.TargetInGirdCondition;
import com.merlin204.avalon.entity.condition.TargetInGirdCondition.Rectangle;
import org.merlin204.mimic.entity.MimicPatch;
import org.merlin204.mimic.epicfight.MimicAnimations;

public class MimicCombatBehaviors {
   public static final Builder<MimicPatch<?>> PHASE1 = AvalonCombatBehaviors.builder()
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(50.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder().animationBehavior(MimicAnimations.SKILL_1).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(5, -5, -5, 5)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_1))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(1.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_1).withinDistance(0.0, 50.0))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_1))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(50.0F)
            .cooldown(50)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder()
                  .animationBehavior(MimicAnimations.SKILL_1)
                  .predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(20, -20, -20, 20)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_1))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(10.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(
               Behavior.builder().animationBehavior(MimicAnimations.SKILL_1).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(5, -5, -5, 5)}))
            )
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(10.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(
               Behavior.builder().animationBehavior(MimicAnimations.SKILL_1).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(3, -3, -3, 3)}))
            )
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(10.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(3, -3, -3, 3)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_1))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(10.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(3, -3, -3, 3)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_1))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(10.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder()
                  .behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT)
                  .predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(3, -3, -3, 3)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_1))
      );
   public static final Builder<MimicPatch<?>> PHASE3 = AvalonCombatBehaviors.builder()
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(500.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder().animationBehavior(MimicAnimations.SKILL_3).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(5, -5, -5, 5)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(500.0F)
            .cooldown(50)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder()
                  .animationBehavior(MimicAnimations.SKILL_3)
                  .predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(20, -20, -20, 20)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(500.0F)
            .cooldown(50)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder()
                  .animationBehavior(MimicAnimations.SKILL_3)
                  .predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(20, -20, -20, 20)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(100.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(
               Behavior.builder().animationBehavior(MimicAnimations.SKILL_3).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(5, -5, -5, 5)}))
            )
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(100.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.TRY_PLAY_COMBO))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(
               Behavior.builder().animationBehavior(MimicAnimations.SKILL_3).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(3, -3, -3, 3)}))
            )
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(100.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(3, -3, -3, 3)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(100.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY).predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(3, -3, -3, 3)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_CAN_HIT_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
      )
      .newBehaviorSeries(
         BehaviorSeries.builder()
            .weight(100.0F)
            .cooldown(10)
            .canBeInterrupted(false)
            .looping(false)
            .nextBehavior(
               Behavior.builder()
                  .behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT)
                  .predicate(new TargetInGirdCondition(new Rectangle[]{new Rectangle(3, -3, -3, 3)}))
            )
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().behavior(MimicConsumers.PLAY_RANDOM_COPY_WITHOUT_HIT))
            .nextBehavior(Behavior.builder().animationBehavior(MimicAnimations.SKILL_3))
      );
}
