package com.dmc.invincible_dmc.client.config;

import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.common.ForgeConfigSpec.BooleanValue;
import net.minecraftforge.common.ForgeConfigSpec.Builder;
import net.minecraftforge.common.ForgeConfigSpec.EnumValue;

public final class YamatoClientConfig {
   public static final ForgeConfigSpec SPEC;
   public static final BooleanValue JUDGEMENT_CUT_END_CAMERA_ENABLED;
   public static final EnumValue<YamatoClientConfig.JudgementCutBladeTrailQuality> JUDGEMENT_CUT_BLADE_TRAIL_QUALITY;
   public static final EnumValue<YamatoClientConfig.JudgementCutSequenceStyle> JUDGEMENT_CUT_SEQUENCE_STYLE;
   public static final EnumValue<YamatoClientConfig.PortalParticleStyle> PORTAL_PARTICLE_STYLE;
   public static final EnumValue<YamatoClientConfig.ComboSlashStyle> COMBO_SLASH_STYLE;

   private YamatoClientConfig() {
   }

   static {
      Builder builder = new Builder();
      builder.comment("Yamato client visual settings").push("yamato");
      JUDGEMENT_CUT_END_CAMERA_ENABLED = builder.comment("Enable the cinematic camera for Judgement Cut End.").define("judgement_cut_end_camera_enabled", true);
      JUDGEMENT_CUT_BLADE_TRAIL_QUALITY = builder.comment(
            new String[]{
               "JCBladeTrail amount generated by JudgementCutParticle.", "HIGH keeps the original amount, MEDIUM reduces it by 30%, LOW reduces it by 50%."
            }
         )
         .defineEnum("judgement_cut_blade_trail_quality", YamatoClientConfig.JudgementCutBladeTrailQuality.HIGH);
      JUDGEMENT_CUT_SEQUENCE_STYLE = builder.comment(
            new String[]{
               "Sequence particle style used by normal and perfect Judgement Cut effects.",
               "NORMAL uses the original particles; DMC4 uses the DMC4 particle variants."
            }
         )
         .defineEnum("judgement_cut_sequence_style", YamatoClientConfig.JudgementCutSequenceStyle.NORMAL);
      PORTAL_PARTICLE_STYLE = builder.comment(
            new String[]{
               "Portal particle style used by portals created by this player.",
               "ORIGINAL uses the sprite-sequence portal; END_PORTAL uses the procedural End Portal variant."
            }
         )
         .defineEnum("portal_particle_style", YamatoClientConfig.PortalParticleStyle.ORIGINAL);
      COMBO_SLASH_STYLE = builder.comment(
            new String[]{"Visual style used by Yamato combo slash effects.", "COMBO_SLASH_STYLE_1 is the default style; COMBO_SLASH uses the alternate style."}
         )
         .defineEnum("combo_slash_style", YamatoClientConfig.ComboSlashStyle.COMBO_SLASH_STYLE_1);
      builder.pop();
      SPEC = builder.build();
   }

   public static enum ComboSlashStyle {
      COMBO_SLASH_STYLE_1,
      COMBO_SLASH;
   }

   public static enum JudgementCutBladeTrailQuality {
      HIGH(1.0),
      MEDIUM(0.7),
      LOW(0.5);

      private final double multiplier;

      private JudgementCutBladeTrailQuality(double multiplier) {
         this.multiplier = multiplier;
      }

      public double multiplier() {
         return this.multiplier;
      }
   }

   public static enum JudgementCutSequenceStyle {
      NORMAL,
      DMC4;
   }

   public static enum PortalParticleStyle {
      ORIGINAL,
      END_PORTAL;
   }
}
